# — Taps —
tap 'homebrew/aliases' # github.com/Homebrew/homebrew-aliases
tap 'homebrew/command-not-found' # github.com/Homebrew/homebrew-command-not-found
tap 'homebrew/services' # github.com/Homebrew/homebrew-services
tap 'caskroom/fonts' # github.com/caskroom/homebrew-fonts

# — Formulae —
brew 'bash-completion@2' # github.com/scop/bash-completion (for Bash >4 use bash-completion instead)
brew 'ccat' # github.com/jingweno/ccat
brew 'coreutils', args: ['with-default-names'] # gnu.org/software/coreutils/coreutils
brew 'docker-completion' # github.com/docker/docker
brew 'ffmpeg', args: ['with-faac'] # ffmpeg.org
brew 'findutils', args: ['with-default-names'] # gnu.org/software/findutils
brew 'git' # git-scm.org
brew 'gnupg' # gnupg.org
brew 'grep', args: ['with-default-names'] # gnu.org/software/grep
brew 'imagemagick', args: ['with-libtiff', 'with-webp'] # imagemagick.org/script/index.php
brew 'magic-wormhole' # github.com/warner/magic-wormhole
brew 'make', args: ['with-default-names'] # www.gnu.org/software/make/
brew 'nano' # nano-editor.org
brew 'nmap' # nmap.org
brew 'openssl' # openssl.org
brew 'ruby-completion' # github.com/mernen/completion-ruby
brew 'screen' # gnu.org/software/screen
brew 'shellcheck' # www.shellcheck.net/
brew 'ssh-copy-id' # openssh.com
brew 'trash' # hasseg.org/trash
brew 'tree' # mama.indstate.edu/users/ice/tree
brew 'wget', args: ['with-iri'] # gnu.org/software/wget

# — Casks —
cask '1password' # 1password.com
cask 'alfred' # www.alfredapp.com
cask 'angry-ip-scanner' # angryip.org
cask 'betterzip' # macitbetter.com
cask 'coconutbattery' # www.coconut-flavour.com/coconutbattery/
cask 'colorpicker-skalacolor' # bjango.com/mac/skalacolor
cask 'devdocs' # github.com/egoist/devdocs-app
cask 'docker' # docker.io
cask 'etcher' # etcher.io
cask 'fork' # https://git-fork.com/
cask 'franz' # meetfranz.com
cask 'google-chrome' # google.com/chrome
cask 'gpg-suite' # gpgtools.org
cask 'handbrake' # handbrake.fr
cask 'hyper' # hyper.is
cask 'imageoptim' # imageoptim.com/mac
cask 'insomnia' # insomnia.rest
cask 'kap' # getkap.co
cask 'kitematic' # kitematic.com
cask 'notion' # https://www.notion.so/
cask 'qlcolorcode' # github.com/n8gray/QLColorCode
cask 'qlimagesize' # github.com/Nyx0uf/qlImageSize
cask 'qlmarkdown' # github.com/toland/qlmarkdown
cask 'qlstephen' # github.com/whomwah/qlstephen
cask 'quicklook-csv' # github.com/p2/quicklook-csv
cask 'quickjson' # github.com/johan/QuickJSON
cask 'rocket' # matthewpalmer.net/rocket
cask 'sequel-pro' # sequelpro.com
cask 'spectacle' # spectacleapp.com
cask 'spotify' # spotify.com
cask 'superduper' # www.shirt-pocket.com/SuperDuper/SuperDuperDescription.html
cask 'suspicious-package' # mothersruin.com/software/SuspiciousPackage
cask 'transmission' # transmissionbt.com
cask 'virtualbox' # virtualbox.org
cask 'visual-studio-code' # code.visualstudio.com
cask 'vlc' # videolan.org/vlc

# — Fonts —
cask 'font-fira-code'
cask 'font-fira-mono'
cask 'font-fira-sans'
cask 'font-hack'
cask 'font-ibm-plex'
