#!/usr/bin/env bash

modules=(
  babel
  babel-eslint
  eslint
  forever
  grunt-cli
  gulp
  mklicense
  mocha
  nativefier
  node-gyp
  nodemon
  npm
  speed-test
  vtop
  webpack
  webpack-validator
  yo
)

generators=(
  generator-devine-project
  generator-generator
)

npm install -g ${modules[@]}
npm install -g ${generators[@]}
