#!/usr/bin/env bash

modules=(
  bower
  cordova
  forever
  grunt-cli
  gulp
  nodemon
  pageres-cli
  speed-test
  surge
  tmi
  trash-cli
  uncss
  vtop
  webpack
  yo
)

generators=(
  generator-devine-project
  generator-generator
)

npm install -g ${modules[@]}
npm install -g ${generators[@]}
