#!/usr/bin/env bash

modules=(
  bower
  caniuse-cmd
  cordova
  fffast
  grunt-cli
  gulp
  nodemon
  pageres
  slap
  speed-test
  surge
  tmi
  uncss
  vtop
  webpack
  yo
)

generators=(
  generator-meanstack
)

npm install -g ${modules[@]}
npm install -g ${generators[@]}
