#!/usr/bin/env bash
sudo -v

GEMS=(
  bitters
  bourbon
  compass
  cocoapods
  facter
  glynn
  jekyll
  neat
  sass
  scss-lint
  terminal-notifier
)

for gem in ${GEMS[@]}; do
  gem install $gem
done
